name: bleck_markdown
description: Markdown Preview for Flutter project
version: 0.0.1
homepage: https://github.com/TimothyGCY/bleck_markdown

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_html: ^2.2.1
  markdown: ^6.0.1
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

