dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_html: ^3.0.0-alpha.6
  flutter_inappwebview: ^6.0.0-beta.22
  html: ^0.15.4
  markdown: ^7.1.0
  url_launcher: ^6.1.10
description: Markdown Preview for Flutter project
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
environment:
  flutter: ">=1.17.0"
  sdk: '>=2.19.1 <3.0.0'

flutter:


homepage: https://github.com/TimothyGCY/bleck_markdown
name: bleck_markdown
# The following section is specific to Flutter packages.
version: 0.0.1

